/*
 * HTMLHelp.java
 *
 * Created on 19. Januar 2006, 17:54
 */

package io.github.tanguygab.logicsim3.gui;

import io.github.tanguygab.logicsim3.I18N;
import io.github.tanguygab.logicsim3.LSProperties;
import io.github.tanguygab.logicsim3.Lang;

import javax.swing.*;
import java.awt.AWTEvent;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.*;
import java.io.File;

/**
 *
 * @author atetzl
 */
public class HTMLHelp extends JFrame implements ActionListener {
	private static final long serialVersionUID = 4292051858178374722L;
	private javax.swing.JButton jButton_ok;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextPane jTextPane1;


	/** Creates new form HTMLHelp */
	public HTMLHelp() {
		String language = LSProperties.getInstance().getProperty("language", "en");
		Dimension scrSize;
		int width = 800, height = 600;

		getContentPane().setLayout(new BorderLayout(0, 0));
		initComponents();
		enableEvents(AWTEvent.MOUSE_EVENT_MASK);

		scrSize = Toolkit.getDefaultToolkit().getScreenSize();
		setLocation((scrSize.width / 2) - (width / 2), (scrSize.height / 2) - (height / 2));
		setSize(width, height);
		setTitle("LogicSim " + I18N.tr(Lang.HELP));

		try {
			File docs = new File("docs");
			File[] files = docs.listFiles();
			assert files != null;
			String url = new File("docs/en.html").getAbsolutePath();
			// Anleitung in der eingestellten Sprache finden
            for (File file : files) {
                if (file.getName().startsWith(language) && file.getName().endsWith(".html")) {
                    url = file.getAbsolutePath();
                }
            }

			url = url.replaceAll("\\\\", "/");
			url = "file:///" + url;
			url = url.replaceAll(" ", "%20");
			jTextPane1.setPage(url);
		} catch (Exception ex) {
			ex.printStackTrace();
			setVisible(false);
			dispose();
		}
		setVisible(true);
	}

	@Override
	public void processMouseEvent(MouseEvent e) {
		super.processMouseEvent(e);
		if (e.getID() == MouseEvent.MOUSE_CLICKED) {
			setVisible(false);
			dispose();
		}
	}

	@Override
	public void processWindowEvent(WindowEvent e) {
		// super.processWindowEvent(e);
		if (e.getID() == WindowEvent.WINDOW_CLOSING) {
			dispose();
		}
	}



	@Override
	public void actionPerformed(ActionEvent e) {}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jButton_ok = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jTextPane1.setContentType("text/html;charset=UTF-8");
		
		jButton_ok.setText("OK");
		jButton_ok.addActionListener(evt -> {
			dispose();
			setVisible(false);
		});

		getContentPane().add(jButton_ok, java.awt.BorderLayout.SOUTH);

		jTextPane1.setEditable(false);
		jTextPane1.setMinimumSize(new java.awt.Dimension(400, 300));
		jScrollPane1.setViewportView(jTextPane1);

		getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

		pack();
	}


}
